[package]
name = "tap"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
cursive = { version = "0.20", features = ["crossterm-backend", "toml"] }
lofty = { version = "0.11" }
rodio = { git = "https://github.com/timdubbins/rodio", features = ["symphonia-all"], default-features = false }