[package]
name = "tap"
version = "0.1.1"
authors = ["Tim Dubbins <timdubbins@gmail.com>"]
description = "tap is a TUI-audio-player."
documentation = "https://github.com/timdubbins/tap"
homepage = "https://github.com/timdubbins/tap"
repository = "https://github.com/timdubbins/tap"
keywords = ["audio", "player"]
categories = ["command-line-utilities"]
license = "Unlicense OR MIT"
edition = "2021"

[[bin]]
bench = false
path = "src/main.rs"
name = "tap"

[dependencies]
anyhow = "1.0"
async-std = "1.12.0"
clap = { version = "4.1.8", features = ["derive"] }
cursive = { version = "0.20", features = ["ncurses-backend", "toml"] }
lofty = "0.14.0"
rand = "0.8.5"
rodio = { git = "https://github.com/timdubbins/rodio", features = ["symphonia-all"], default-features = false }